### ISSUE TITLE
How to fix the building error: "klee_add_llvm_loadable_module not implemented with llvm-config"

### ISSUE THREAD

**Issue by Hanseltu** [por-se/por-se#2]
Hi, 

Thanks for your interesting paper and the tool!

I tried to build `por-se` natively but I got the following error when I executing `cmake -DENABLE_SOLVER_STP=ON -DENABLE_POSIX_RUNTIME=ON -DENABLE_KLEE_UCLIBC=ON -DKLEE_UCLIBC_PATH=/home/haoxin/disk-smu/research/klee-env/klee-uclibc -DLLVM_CONFIG_BINARY=/usr/bin/llvm-config-9 -DLLVMCC=/usr/bin/clang-9 -DLLVMCXX=/usr/bin/clang++-9 -DCMAKE_BUILD_TYPE=Debug ..`.
```
CMake Error at cmake/find_llvm.cmake:254 (message):
  klee_add_llvm_loadable_module not implemented with llvm-config
Call Stack (most recent call first):
  lib/Module/CMakeLists.txt:63 (klee_add_llvm_loadable_module)
```

Does the error mean I need to modify LLVM compiler's code to support the function `klee_add_llvm_loadable_module` before successfully building `por-se`? How can I fix this issue?

Thanks,
Haoxin

**Comment by jbuening** [comment]
Hi @Hanseltu, thanks for your interest in our tool!

The error message "klee_add_llvm_loadable_module not implemented with llvm-config" refers to the fact that we did not implement the cmake function `klee_add_llvm_loadable_module` when using `-DLLVM_CONFIG_BINARY` instead of `-DUSE_CMAKE_FIND_PACKAGE_LLVM=On`.

Most likely, you do not need to implement the function `klee_add_llvm_loadable_module` as it is only used for testing the custom `LiveRegister` pass in PORSE, but is not required for building or running the tool itself.

Thus, I suggest one of the following two ways forward:
1. comment out the following lines: https://github.com/por-se/por-se/blob/9e7364c00b85f62b7fd1c88fef174d157a247bef/lib/Module/CMakeLists.txt#L63-L68
This will probably let a few tests in `test/Passes/LiveRegister` fail, but I cannot think of any further consequence right now.
2. Use `-DUSE_CMAKE_FIND_PACKAGE_LLVM=On` instead of `-DLLVM_CONFIG_BINARY=/usr/bin/llvm-config-9` when configuring the build (the latter method was [recently removed from KLEE](https://github.com/klee/klee/pull/1569), we just stopped using it for PORSE a few years earlier).

I hope that helps!

**Comment by Hanseltu** [comment]
Hi, @jbuening, thanks for your super speedy responses! Your solution worked well for me to fix the building error!

However, when I continued to execute `make`, there was a compilation error

```
...
In file included from /home/haoxin/disk-smu/research/github/por-se/lib/Por/csd2.cpp:6:0:
/home/haoxin/disk-smu/research/github/por-se/include/util/at_scope_exit.h: At global scope:
/home/haoxin/disk-smu/research/github/por-se/include/util/at_scope_exit.h:10:57: error: invalid use of ‘this’ at top level
   ~at_scope_exit_t() noexcept(noexcept(static_cast<F&>(*this)())) {
                                                         ^~~~
...
```

I am not sure what the problem is. Do I use the wrong compilation option (e.g., c++ standard) or compiler version (I tried clang-6 and clang-9)?  Could you please share with me the building command if you have any backups? Many thanks again!

Best,
Haoxin

**Comment by jbuening** [comment]
Hi @Hanseltu, I do not have the exact invocation at the moment (given that we used our [workspace](https://github.com/por-se/workspace) scripts for building and I don't have a version of our [CAV 2020 Artifact](https://zenodo.org/records/5771252) ready that I can quickly spin up), sorry. But I think your guess goes into the right direction!

Note that the clang compiler that you supply to CMake (just as in KLEE) via `-DLLVMCXX` is not used to build PORSE itself, but just some bitcode for various parts of the runtime. Instead, your system compiler (typically GCC) is used. We always used fairly recent (at the time) GCC versions to compile KLEE / PORSE itself, so I tried around a bit and saw that the error indeed occurs if you compile with e.g. GCC 8.4, but not starting from GCC 9.1 and indeed also not with clang 9.
See [this godbolt.org test](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGIM6SuADJ4DJgAcj4ARpjE/gCspAAOqAqETgwe3r7%2ByanpAiFhkSwxcWaJdpgOGUIETMQEWT5%2BAVU1AnUNBEUR0bEJtvWNzTltwz2hfaUDFQCUtqhexMjsHOYAzKHI3lgA1CYbbgQAnkmYAPoExEyECofYJhoAgpvbu5gHR16OtIQnDyerxezDYCiSTFWex%2BdAOAHYrC8ngBOAiYFhJAxow7HM6MVifABigKRGmRCmuXgceyYBAuCjQ5wumFUhCuexAeySxDwADdaUT4YjgciUbT6YzLiy2QQIIS9lQvAxkHMOXtCRAKegQCAWKheZhqEqVaqTAj4QARIHWskogB%2B4oZqCZ0rpstVDFQLNWSVlnu9mF9mvqjmQF1EFJxxLMADYHhAAFQEBB4BRzCBzTNCm2i21kim0vBhiMEKPmOMbbCJ5Op9NzQ7ClFNuFW0milsNm0itEYrGYHGnc6gokkkVMH6oPYsJgAa0ujslzNZsvliuVpoROZRxEwBGWDBpdKdLuXVxxWp1WFEJzPR2JlfjF91%2BsNa5NnbbZtbrw7pOeoQIKdbgYDNsxePYIJpCc9meL4LWhX4dWnOcLgXZ0pWXCATHiKx4gtUCzQsA5wMg0idz3YgD0pfsNmFUiv3rWigTI3d9z2LgPx/C0OAWWhOHiXg/A4LRSFQTg3Gsaw9gUJYVk%2BTYeFIAhNB4hYZxAeINgAOhjZEYw0OFJBjDZJEkOEuCkfROEkQSVNEzheAUEANCUlSFjgWAYEQEAWWqCcyAoCAGmABRlEMTBaCEBBUAAdyExS0AxOhCwEMKwki6K4rsxKkjoAZgAADmkHK8uIcICQc0gSvoYgAHkfii2KhJE3zkGeYgQsq1q6nwITeH4QQRDEdhLIG%2BQlDUOzdC4fRDGMSTLH0PAoicyAFmdRwBCcjgAFparMPYdp2rVDgtUxLGsLg4V4F9iB5LBVozUhiCVRw2AAFVQTxHoWGTllWPQtVCNKIsarLuF4GKbiSTgeF4/jbOEm7OGwVQ/KIYg9lUAqYx2mNJD2YBkGQPYCq0gmIAki7Fr2XBCBIA4zA2Lg5l4ZSkczUh1OZrSzC4GMYwKswzGRMkNC4MkrI4GzSBYEANm0%2BJkQ2OFEma5GOEc5zXI50gPO81r/PIShgtC8KMqa2HeGqlKGBBi3wZE6r8uRGbnbKirNaq1Akpq%2BrhEy9XAjRtqOu23huoIXrKrGobxFG2RFBUdQkdIXQNlmowUAWmw/hW%2BB1t9DJtr2g6jpOjYzpzq6boNO68AegvntevAPq%2B2gfsWf6RqGXr7bB%2BLIehq34Y4ATSCDsSOFR9GGex3H8cJ4m9mRLSuD2Smc9IWn8AxxnmdZnWtE5hBMCYLA4ievjpd4OXJC4cmNBjMxJGRN/3/fie7KnrWXPZ4%2B9ZeQgEgQ2GNjZBTDv3QOVtva%2B1tlAy2qd3YoAMEYUWTAFBKEaLA3KNVypsEqu7f2A87KtXap1L2kdo5e1jqIeO0gxpJ0mqnXQARUHzWprnZancNrF04KXQ6x0o6nXOlYSwNdRJ13upgTuL1BCt0wJ9b6Tc/pyUBlHYG5sSEQ1IFDJgMMIaj3HpPFGId/JYxxnjAmOw5ory0hoexG8MFYM2gwNMG8qZiJsDvemmMFKH3/qpUgp9z4DCvtZW%2BgwTFeycn/NyakQBGS0hsDQGxkQVA2DGeI8QzAFQKnCKWGxEYiR/kfIJ18zCRIli5aJbN4mkDrmkZwkggA%3D%3D%3D).

Thus, I would suggest you try to upgrade your system GCC to a newer version.

**Comment by Hanseltu** [comment]
Hi @jbuening, thank you for your prompt and helpful suggestions again!

Yes, you are super right. I used `gcc-7.5` to build it so I encountered the compilation error. Now I added the following two lines at the beginning of https://github.com/por-se/por-se/blob/master/lib/Por/CMakeLists.txt, and finally, everything looks ok.

```
set(CMAKE_C_COMPILER "gcc-9")
set(CMAKE_CXX_COMPILER "g++-9")
```

Btw, I am also reading the PORSE paper to understand the technical ideas of PORSE and seek opportunities to migrate the idea to resolve my own research problem, but since I am not a person in formal verification, would you kindly allow me to raise some more detailed questions about the design of PORSE in the following days/weeks? If possible, would you prefer me to raise questions here or drop you emails? Thanks!

Best regards,
Haoxin

**Comment by jbuening** [comment]
Hi @Hanseltu, glad to hear it helped! I will close this for now, since the issue of building PORSE seems resolved. If you run into any technical problems, feel free to open another issue; for the research- or paper-related questions, feel free to drop me an email and I will see how I can help!
